# Applying Deep Learning

In [38]:
import pandas as pd
import os
import numpy as np
np.random.seed(42)
import re
import keras
from keras.models import Sequential
from keras.layers import Dense, Input
from keras.utils import to_categorical

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.metrics import confusion_matrix, classification_report, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

In [4]:
data= pd.read_csv('nutrient_data.csv')
data

name  protein_g     fats_g  \
0                         shepardless-pie   1.800000   1.700000   
1        Lidl_TowerGate_Cookie_Cranberrry   5.100000  22.900000   
2                  chocuer_milk_chocolate   7.700000  36.400000   
3          john-west-tuna-chunks-in-brine   2.689187   1.568333   
4              Lidl_PotatoWaffle_BirdsEye   2.200000   3.504000   
..                                    ...        ...        ...   
575    WholeWheat_Fusilli_pasta_smokedHam   9.300000   2.800000   
576  battered-chicken-balls-aldi-roosters  16.100000   6.800000   
577                          fruit_juice2   0.500000   2.571000   
578  Lidl_Sliced_Irish_Mature_WhiteCheese  27.900000  22.100000   
579                                 pork3  18.000000  29.000000   

     saturated_fats_g  carbohydrates_g  sugars_g  fibres_g   salt_g  \
0              0.2000           9.3648    2.1000    2.0000  0.39000   
1             10.9000          64.4000   45.2000    2.7000  0.67000   
2             15.6420          51.6000   49.7000    2.7670  0.18000   
3              0.4188           7.4144    3.2178    2.9255  0.42756   
4              0.5000          15.3350    0.9000    1.3000  0.58000   
..                ...              ...       ...       ...      ...   
575            1.4000          14.0222    1.6000    1.3880  0.54900   
576            0.8000          13.9000    0.5000    1.0000  0.78000   
577            2.5350           6.2368    9.5000    0.3000  0.48790   
578           13.8000           0.8000    0.2070    0.1950  1.80000   
579            9.5000           0.5000    0.5000    0.0000  3.40000   

     Total Energy_Kcal Nutri_Score  
0             79.00000           A  
1            490.00000           E  
2            569.00000           E  
3            240.54218           B  
4             94.00000           B  
..                 ...         ...  
575          125.71400           A  
576          183.79100           A  
577           44.93200           C  
578          314.00000           D  
579          335.00000           D  

[580 rows x 10 columns]

In [5]:
# Define the target variable 'is_healthy' (1 for 'A' or 'B', 0 otherwise)
data['Healthy'] = data['Nutri_Score'].apply(lambda x: 1 if x in ['A', 'B'] else 0)

In [6]:
# Features: only the nutrient columns, excluding Nutri_Score
features = ['protein_g', 'fats_g', 'saturated_fats_g', 'carbohydrates_g', 'sugars_g', 'fibres_g', 'salt_g', 'Total Energy_Kcal']
X = data[features]
y = data['Healthy']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [39]:
X

protein_g     fats_g  saturated_fats_g  carbohydrates_g  sugars_g  \
0     1.800000   1.700000            0.2000           9.3648    2.1000   
1     5.100000  22.900000           10.9000          64.4000   45.2000   
2     7.700000  36.400000           15.6420          51.6000   49.7000   
3     2.689187   1.568333            0.4188           7.4144    3.2178   
4     2.200000   3.504000            0.5000          15.3350    0.9000   
..         ...        ...               ...              ...       ...   
575   9.300000   2.800000            1.4000          14.0222    1.6000   
576  16.100000   6.800000            0.8000          13.9000    0.5000   
577   0.500000   2.571000            2.5350           6.2368    9.5000   
578  27.900000  22.100000           13.8000           0.8000    0.2070   
579  18.000000  29.000000            9.5000           0.5000    0.5000   

     fibres_g   salt_g  Total Energy_Kcal  
0      2.0000  0.39000           79.00000  
1      2.7000  0.67000          490.00000  
2      2.7670  0.18000          569.00000  
3      2.9255  0.42756          240.54218  
4      1.3000  0.58000           94.00000  
..        ...      ...                ...  
575    1.3880  0.54900          125.71400  
576    1.0000  0.78000          183.79100  
577    0.3000  0.48790           44.93200  
578    0.1950  1.80000          314.00000  
579    0.0000  3.40000          335.00000  

[580 rows x 8 columns]

In [11]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ANN


In [44]:
# Initialise ANN model
classifier = Sequential()

# Adding first input layer and first hidden layer
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu', input_dim=8))

# Adding the second hidden layer
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))

# Adding the output layer
classifier.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))

# Compile the model
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Fitting ANN to training set
classifier.fit(X_train, y_train, epochs=100, batch_size=32, verbose=1)

#evaluate model on test set
_,accuracy = classifier.evaluate(X_test, y_test)
print("ANN Accuracy:", accuracy)

#Evaluating Results
confusion_metric= confusion_matrix(y_test, y_pred)
confusion_metric


Epoch 1/100


/opt/anaconda3/envs/tf_env/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step - accuracy: 0.5873 - loss: 0.6951
Epoch 2/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 755us/step - accuracy: 0.6212 - loss: 0.6913
Epoch 3/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 538us/step - accuracy: 0.7216 - loss: 0.6886
Epoch 4/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 491us/step - accuracy: 0.6818 - loss: 0.6858
Epoch 5/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 479us/step - accuracy: 0.6524 - loss: 0.6771
Epoch 6/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.6176 - loss: 0.6697
Epoch 7/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 401us/step - accuracy: 0.6521 - loss: 0.6588
Epoch 8/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step - accuracy: 0.7620 - loss: 0.6368
Epoch 9/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 448us/step - accuracy: 0.8272 - loss: 0.5986
Epoch 10/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - accuracy: 0.8180 - loss: 0.5701
Epoch 11/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.8590 - loss: 0.5148
Epoch 12/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step

array([[43, 10],
       [ 0, 63]])

# ANN with Dropout

In [45]:
from keras.layers import Dropout

classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu', input_dim=8))
classifier.add(Dropout(0.5))  # Dropout of 50%
# Adding the second hidden layer
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))

# Adding the output layer
classifier.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))

# Compile the model
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Fitting ANN to training set
classifier.fit(X_train, y_train, epochs=100, batch_size=32, verbose=1)

#evaluate model on test set
_,accuracy = classifier.evaluate(X_test, y_test)
print("ANN Accuracy with Dropout:", accuracy)

#Evaluating Results
confusion_metric= confusion_matrix(y_test, y_pred)
confusion_metric


Epoch 1/100


/opt/anaconda3/envs/tf_env/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 668us/step - accuracy: 0.6006 - loss: 0.6927
Epoch 2/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - accuracy: 0.6148 - loss: 0.6914
Epoch 3/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 604us/step - accuracy: 0.5652 - loss: 0.6911
Epoch 4/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 685us/step - accuracy: 0.6280 - loss: 0.6877
Epoch 5/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 634us/step - accuracy: 0.6083 - loss: 0.6859
Epoch 6/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 700us/step - accuracy: 0.5933 - loss: 0.6841
Epoch 7/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 568us/step - accuracy: 0.6241 - loss: 0.6779
Epoch 8/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 512us/step - accuracy: 0.6334 - loss: 0.6705
Epoch 9/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - accuracy: 0.6150 - loss: 0.6678
Epoch 10/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 634us/step - accuracy: 0.6247 - loss: 0.6579
Epoch 11/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.6148 - loss: 0.6513
Epoch 12/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 608us/step

array([[43, 10],
       [ 0, 63]])

# CNN

In [46]:
from keras.layers import Conv1D, MaxPooling1D, Flatten

model = Sequential()
model.add(Conv1D(filters=32, kernel_size=2, activation='relu', input_shape=(8, 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Fitting CNN to training set
model.fit(X_train, y_train, epochs=100, batch_size=32, verbose=1)

#evaluate model on test set
_,accuracy = model.evaluate(X_test, y_test)
print("CNN Accuracy:", accuracy)

#Evaluating Results
confusion_metric= confusion_matrix(y_test, y_pred)
confusion_metric


Epoch 1/100


/opt/anaconda3/envs/tf_env/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step - accuracy: 0.4007 - loss: 1.1200
Epoch 2/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step - accuracy: 0.4280 - loss: 0.6576
Epoch 3/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 565us/step - accuracy: 0.6265 - loss: 0.5922
Epoch 4/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - accuracy: 0.7129 - loss: 0.6000
Epoch 5/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step - accuracy: 0.7297 - loss: 0.5776
Epoch 6/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 505us/step - accuracy: 0.7111 - loss: 0.5950
Epoch 7/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - accuracy: 0.7211 - loss: 0.5389
Epoch 8/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step - accuracy: 0.7108 - loss: 0.5612
Epoch 9/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 502us/step - accuracy: 0.7784 - loss: 0.5246
Epoch 10/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 476us/step - accuracy: 0.7985 - loss: 0.5425
Epoch 11/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step - accuracy: 0.7836 - loss: 0.5219
Epoch 12/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step

array([[43, 10],
       [ 0, 63]])

# LSTM

In [47]:
from keras.layers import LSTM

model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(8, 1)))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

#fitting to model
model.fit(X_train,y_train, epochs=100, batch_size=32, verbose=1)

#evaluate model on test set
_,accuracy = model.evaluate(X_test, y_test)
print("LSTM Accuracy:", accuracy)

#Evaluating Results
confusion_metric= confusion_matrix(y_test, y_pred)
confusion_metric

Epoch 1/100


/opt/anaconda3/envs/tf_env/lib/python3.10/site-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6371 - loss: 7.7361  
Epoch 2/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6201 - loss: 2.7324 
Epoch 3/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5544 - loss: 0.8838 
Epoch 4/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7529 - loss: 0.7322 
Epoch 5/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7254 - loss: 0.6057 
Epoch 6/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8033 - loss: 0.5232 
Epoch 7/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8146 - loss: 0.4916 
Epoch 8/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8423 - loss: 0.4122 
Epoch 9/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8814 - loss: 0.3613 
Epoch 10/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8837 - loss: 0.3433 
Epoch 11/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8585 - loss: 0.3619 
Epoch 12/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy:

array([[43, 10],
       [ 0, 63]])